user-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则

server:
  port: 7777
spring:
  servlet:
    multipart:
      max-file-size: 1MB #限定文件上传大小
      max-request-size: 5MB