spring:
    datasource:
        url: jdbc:mysql://localhost:3306/yp_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: "root"
        password: "000000"
        driver-class-name: com.mysql.cj.jdbc.Driver
