spring:
  rabbitmq:
    host: 192.168.10.123 # 主机名
    port: 5672 # 端口
    virtual-host: ypblog # 虚拟主机
    username: admin # 用户名
    password: 123 # 密码
    listener:
      simple:
        prefetch: 1 # 每次只能获取一条消息，处理完成才能获取下一个消息