#server:
#  port: 7777
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/yp_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: "root"
#    password: "000000"
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#    host: localhost
#    port: 6379
#    database: 1
#    password: passwd
#  servlet:
#    multipart:
#      max-file-size: 1MB #限定文件上传大小
#      max-request-size: 5MB
#  main:
#    allow-circular-references: true
#mybatis-plus:
#  configuration:
#    # 日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      logic-delete-field: delFlag #数据库的逻辑删除字段
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#      id-type: auto
#oss:  #七牛云OSS
#  accessKey: xxxx
#  secretKey: xxxx
#  bucket: yp-blog
#
#fdfs: #fastDFS
#  so-timeout: 1501 # 超时时间
#  connect-timeout: 601 # 连接超时时间
#  thumb-image: # 缩略图
#    width: 60
#    height: 60
#  tracker-list: # tracker地址：你的虚拟机服务器地址+端口（默认是22122）
#    - 192.168.10.123:22122